### ISSUE TITLE
Jasmine 2.0

### ISSUE THREAD

**Issue by noelrappin** [modeset/teaspoon#160]
The Jasmine 2.0 branch is well behind, and doesn't seem to match the new Jasmine boot structure. Are there plans to update to Jasmine 2.0, do you need somebody to work on it?

**Comment by mikepack** [comment]
Closing. On the roadmap for 1.0. Would gladly accept a PR.

**Comment by mikepack** [comment]
1.0 has been released and support for Jasmine 2 has been added.
