### ISSUE TITLE
Add support for middleman.

### ISSUE THREAD

**Issue by jejacks0n** [modeset/teaspoon#210]
At RailsConf 2014 there was a good talk by @bradgessler about Middleman. I think it would be useful to have a friendly way to use Teaspoon in Middleman.

```ruby
gem 'teaspoon', require: 'teaspoon/middleman'
```

Teaspoon assumes that ActiveSupport is available, which works out well since Middleman has it as a dependency. The second is the generator, which should work pretty will with some abstractions since Thor is also available.. so in theory this won't be too hard, but there's some complexity that might exist that I don't know. This is where I wanted to capture the idea.

**Comment by mikepack** [comment]
@jejacks0n should we take a stab at this pre 1.0? What was holding this up before?

**Comment by mikepack** [comment]
Going to close this. After some thought, we won't be able to support support Middleman, Sinatra or any Rails-less environment until we do some major refactoring to pull Rails out of Teaspoon, which is non-trivial. This will eventually happen, but not for the foreseeable future.
