### ISSUE TITLE
using jasmine 2.0.0 failing with Uncaught TeaspoonError: Jasmine not found 

### ISSUE THREAD

**Issue by skbailey** [modeset/teaspoon#215]
ruby 2.1.1
rails 4.1.0

created a brand new rails app:
```
rails new teaspoon_jasmine2 --skip-active-record
```

installed the teaspoon:
```
rails generate teaspoon:install
```

updated teaspoon_env.js with:

```
suite.use_framework :jasmine, "2.0.0"
suite.javascripts = ["jasmine/2.0.0", "teaspoon-jasmine"]
```

and ensured all the files are precompiled via:
```
$ cat config/initializers/assets.rb 
Rails.application.config.assets.precompile += %w( teaspoon.css jasmine/2.0.0.js teaspoon-jasmine.js teaspoon-teaspoon.js)
```

running rake teaspoon fails with:

```
Uncaught TeaspoonError: Jasmine not found -- use `suite.use_framework :jasmine` and adjust or remove the `suite.javascripts` directive. teaspoon-jasmine.js?body=1:1158
Uncaught ReferenceError: describe is not defined 
```

when running the rails server on /teaspoon we get the same error.

The jasmine2.0.0 file is loaded correctly from the asset pipeline though.

**Comment by coderjonny** [comment]
+1 :+1: How's this coming along?

**Comment by VitorHP** [comment]
:+1:

**Comment by rstudner** [comment]
+1 :)

**Comment by jejacks0n** [comment]
It's painful, but I'll try to get back into it sometime soon.

**Comment by samu** [comment]
:+1:

**Comment by coderjonny** [comment]
:+1: @samu ^

**Comment by jejacks0n** [comment]
closing this.. we may get to this before a 1.0 release.

**Comment by Sinetheta** [comment]
So, I'm guessing that 2.0 didn't make it? Following docs results in tears.

**Comment by mikepack** [comment]
Jasmine 2 support is absolutely in Teaspoon 1.0.

**Comment by Sinetheta** [comment]
Thanks @mikepack, I saw that when I re-read and discovered that factories like `gem 'teaspoon-jasmine` are now separate.
