### ISSUE TITLE
RequireJS and Coverage?

### ISSUE THREAD

**Issue by davestevens** [modeset/teaspoon#220]
I've been trying to get Teaspoon to work with both RequireJS and Coverage.

I can get both working independently, but it seems the what i switch the `boot_partial` to `boot_require_js` and try and run the specs with coverage the specs run but the coverage coming back on `result` in `lib/teaspoon/runner.rb` is always `nil`.

I tried to have a look into it and it seems that the `add?` method in `Teaspoon::Instrumentation` never returns true when using RequireJS so no files are being marked for coverage.

Looking at `asset_url` in `lib/teaspoon/suite.rb` the `asset_url` is being appended with `?instrument=1` for my js files.

Have you had any problems with this before? or are you able to point me in the right direction?

**Comment by jejacks0n** [comment]
This is sort of in the works, but we have to figure out how best to do it.. check #277 if you want to track that conversation.

**Comment by davestevens** [comment]
Thanks for getting back about this, I've just made a pull request #315 which seems to allow requirejs to be used along with the coverage.
