### ISSUE TITLE
Expected vs actual not being display in QUnit tests

### ISSUE THREAD

**Issue by cwick** [modeset/teaspoon#225]
The teaspoon test runner doesn't show me expected vs actual results for this simple test:

```
module("Teaspoon test")

test "Expected vs actual", ->
  equal "foo", "bar"
```

Here is what Teaspoon outputs:
![screen shot 2014-05-12 at 5 53 35 pm](https://cloud.githubusercontent.com/assets/477604/2952329/18487ffe-da39-11e3-8c89-f57bde933a35.png)

And here is what the test runner that comes built-in to QUnit looks like:
![screen shot 2014-05-12 at 5 44 05 pm](https://cloud.githubusercontent.com/assets/477604/2952264/ef2d8584-da37-11e3-8661-dcee0b720527.png)

Is Teaspoon supposed to show expected vs actual, or am I doing something wrong?

**Comment by mikepack** [comment]
Closing. Addressed in #316.
