### ISSUE TITLE
Private block host on CircleCi running Selenium

### ISSUE THREAD

**Issue by tarebyte** [modeset/teaspoon#229]
Hi There,

I know this is probably more of a CircleCi question but since I'm using teaspoon I thought I'd ask.

I'm trying to use Selenium (yah I know) and when I run `bundle exec teaspoon` I get the following error.

```
listening on 0.0.0.0:60473, CTRL+C to stop
Teaspoon running default suite at http://127.0.0.1:60473/teaspoon/default
/home/ubuntu/shopify/lib/extensions/net_http.rb:23:in `on_connect_with_block_private_host': Connection to private host 127.0.0.1 blocked (ip 127.0.0.1) (PublicHost::PrivateHostException)
```

Any idea how I can fix this?

**Comment by hakunin** [comment]
Hey @tarebyte, I am trying to make Teaspoon work with CircleCI and getting this, can you share some knowledge?
https://github.com/modeset/teaspoon/issues/427
