### ISSUE TITLE
Updating to teaspoon 0.8.0 breaks chai contain/include assertions

### ISSUE THREAD

**Issue by arfl** [modeset/teaspoon#234]
I updated to teaspoon 0.8.0 and use the chai version included in this gem. The included chai version has a bug in it, described here https://github.com/chaijs/chai/issues/239
The chai version 1.9.1 does fix it.

**Comment by mikepack** [comment]
Thanks for the notice. Going to close this as it's an issue with Chai. In future versions of Teaspoon, we'll allow multiple versions of libraries, so upgrading Teaspoon won't force your hand in upgrading assertion libraries. You can, of course, put any version of Chai in your project's `vendor/assets` and require them in your **spec_helper.coffee**.
