### ISSUE TITLE
DEPRECATION WARNING! on istanbul coverage report

### ISSUE THREAD

**Issue by kunalmawade** [modeset/teaspoon#268]
![screen shot 2014-09-29 at 2 34 44 pm](https://cloud.githubusercontent.com/assets/1070127/4448038/c48c3da2-480f-11e4-8ec0-0a62944a2b74.png)
When `teaspoon --coverage=default` is executed, teaspoon generates coverage and displays above warning on console. The teaspoon version is 0.8.0 and  istanbul version is 0.3.2.
It looks like teaspoon does not pass arguments in right order to istanbul.

**Comment by jejacks0n** [comment]
this should be fixed now.
