### ISSUE TITLE
`url.shellescape` breaks PhantomJS driver

### ISSUE THREAD

**Issue by nalbion** [modeset/teaspoon#271]
As per [this StackOverflow post](http://stackoverflow.com/questions/25959683/ruby-teaspoon-unknown-default-suite) I'm getting the following error when I run teaspoon:

    Teaspoon::UnknownSuite: Unknown suite "default\"

I've managed to track the problem down to `lib/teaspoon/drivers/phantomjs_driver.rb` in `driver_options(url)`.  For some reason (perhaps to URL-encode the suite name?) you call `url.shellescape` which changes the URL from 

    http://127.0.0.1:62848/teaspoon/default?reporter=Console

to 

    http://127.0.0.1:62848/teaspoon/default\?reporter\=Console

If I remove the call to `.shellescape` everything seems to behave.

**Comment by jejacks0n** [comment]
I believe I've resolved this.. I am not using shellescape anymore however, just wrap things in quotes.
