### ISSUE TITLE
Ember.js 1.9 compatibility

### ISSUE THREAD

**Issue by watsonbox** [modeset/teaspoon#291]
I recently upgraded a project to Ember.js 1.9.1 and found that my headless PhantomJS test suite no longer worked.  The fix was to use a [different bind polyfill](https://github.com/watsonbox/facture/commit/21768b69c97214e3adcae9591c9ab74d746518a0).

Thought this might be useful for anyone else running into these issues. Perhaps the stock `bind-poly.js` can be replaced?

**Comment by jejacks0n** [comment]
Yeah, would merge a PR with an update to the readme. =) Thanks!
