### ISSUE TITLE
Boot messages break junit output

### ISSUE THREAD

**Issue by schnittchen** [modeset/teaspoon#293]
With teaspoon -f unit > file.xml as mentioned in the Readme, these messages

Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:41389/teaspoon/default

make the start of the .xml.

**Comment by schnittchen** [comment]
Maybe this could be solved with a --output-file option. One could also argue that the boot messages belong in stderr, but given that a lot of stuff can happen when rails is booted, I would prefer the --output-file option (I actually have another stupid debugging output on every Rails boot here in stdout...)

**Comment by jejacks0n** [comment]
there's a suppress_log flag, which is to be used in conjunction. `-q`

**Comment by jejacks0n** [comment]
(I think this works to disable all output except the spec output)

**Comment by schnittchen** [comment]
Wow crazy are you fast! Was just going to post this workaround:

 teaspoon -f junit | awk '/<?xml/{p=1}; p' > foo.xml

**Comment by schnittchen** [comment]
Thank you. -q would work in my case if there wasn't the other stupid debug output...

**Comment by jejacks0n** [comment]
fix the other output -- teaspoon can't fix *everything*. ;-P

**Comment by jejacks0n** [comment]
there is an output file thing in the formatters -- I mean, they can log to a file -- I just don't remember the details!

**Comment by jejacks0n** [comment]
oh, I remember -- this was in rspec I think, so I mimicked that.. it's part of the formatter, so put it in a string -- it splits on the ">". This is covered in the readme, if you want to be pedantic.

```
teaspoon -f "junit>/path/to/output.xml"
```

**Comment by schnittchen** [comment]
Oh cool!
I did not get that at first, obviously. Also, it still needs -q, like

```
teaspoon -q -f "junit>/path/to/output.xml"
```

Maybe just link to this issue ;)
