### ISSUE TITLE
capybara_webkit driver still supported ?

### ISSUE THREAD

**Issue by jvenezia** [modeset/teaspoon#297]
https://github.com/modeset/teaspoon/wiki/Using-Capybara-Webkit
Is it still supported ?

In the teaspoon_env.rb comments, capybara_webkit is not listed as a supported driver.
When I try, I get:
```
Unknown driver: "capybara_webkit"
```

**Comment by ajb** [comment]
Looks like it was recently added. You might want to try bundling teaspoon with `github: 'modeset/teaspoon'`.

**Comment by jvenezia** [comment]
Yep ! works with the lastest version. However I have no output when I run tests with capybara :/ But it's another problem, I'll check this out.

Thanks !
