### ISSUE TITLE
Teaspoon Hangs frequently in headless runs using PhantomJS.

### ISSUE THREAD

**Issue by bramski** [modeset/teaspoon#299]
We're finding that teaspoon 0.8.0 basically doesn't exit about 1 out of every 4 or 5 circleCI runs.  The tests are all passing.  Any ideas?

![screen shot 2015-01-26 at 4 36 09 pm](https://cloud.githubusercontent.com/assets/421781/5911361/8bc31dde-a579-11e4-9bba-71f093e43588.png)

**Comment by jejacks0n** [comment]
No, I'm not sure -- and it's not been reported that I know of before. would be curious if you can get to the bottom of it and provide an actionable though.

**Comment by bramski** [comment]
We're trying selenium over here for a bunch of runs to see if that's the problem.  I have heard of occasional issues of PhantomJS hanging.  Most of our rails tests run on chrome, not headless.

**Comment by jejacks0n** [comment]
Yeah, phantom is sort of lagging behind, and that's a bummer because it's far more efficient. Let me know what you find, I'd be interested.

**Comment by bramski** [comment]
Yes.  This is for sure PhantomJS causing problems.  We're getting no hangs running selenium.  I've updated the title.  Perhaps some documentation of this issue is all that's appropriate?  I'm uncertain if this will be the case for everyone.

**Comment by jejacks0n** [comment]
I haven't really seen it before, but I'm tagging the issue as information and closing it for now. Could be an odd setup or bad phantomjs build?
