### ISSUE TITLE
unable to launch teaspoon

### ISSUE THREAD

**Issue by pduvvuri** [modeset/teaspoon#300]
bundle exec teaspoon
.../spec/teaspoon_env.rb:7:in `<top (required)>': undefined method `configure' for Teaspoon:Module (NoMethodError)
with latest rails

**Comment by jejacks0n** [comment]
looks like teaspoon isn't loaded in your environment. `configure` is defined on the base Teaspoon module, and if for some reason you're not loading that (you've only loaded teaspoon in your test group for instance) it won't be defined.
