### ISSUE TITLE
Default location of requiring js files is not reachable if you uncomment chai assertion libraries in spec_helper.js

### ISSUE THREAD

**Issue by kareemamin** [modeset/teaspoon#301]
In the default spec_helper.js file if you decide to use Chai and uncomment the following variable assignment:

    // window.assert = chai.assert;
       window.expect = chai.expect;
    // window.should = chai.should();

Then the following section which loads all js in the rails app seems to be unreachable i.e. the files that I expect to be loaded that are in application.js are not loaded. 

    // You can require your own javascript files here. By default this will include everything in application,      however you
    // may get better load performance if you require the specific files that are being used in the spec that tests them.
    //= require application

However, if I move the require application directive to the top of the file it loads the correct files. Not sure if the preprocessor stops once it sees js code but if I comment the variable assignment for Chai it loads the file as expected.

I think it's worthwhile to move the loading of other js files to the top along with the require directives for support libraries to avoid this problem.

**Comment by jejacks0n** [comment]
You're probably right. Do you want to submit a PR?

---
Jeremy Jackson

**Comment by kareemamin** [comment]
Sounds good I'll do that

**Comment by jejacks0n** [comment]
Thanks for helping sort out the confusion!
