### ISSUE TITLE
Can't get formatters to work

### ISSUE THREAD

**Issue by ryanlntn** [modeset/teaspoon#302]
I must be missing something. I just can't seem to get documentation format to work. I have the following in my `teaspoon_env.rb`:

```ruby
Teaspoon.configure do |config|
  config.formatters = "documentation"
end
```

And in my `Guardfile`:

```ruby
guard :teaspoon, cmd: "spring teaspoon -f=documentation" do
  watch(%r{^app/assets/javascripts/(.+).js}) { |m| "#{m[1]}_spec" }
  watch(%r{^spec/javascripts/(.*)})
end
```

And yet I keep getting dot format.

![](http://clrsight.co/rl/io92vz9kdh.png?+)

Any idea what I'm doing wrong?

**Comment by coderjonny** [comment]
try
```
config.formatters = ["documentation"]
```


On Mon, Feb 2, 2015 at 9:36 AM, Ryan Linton <notifications@github.com>
wrote:

> I must be missing something. I just can't seem to get documentation format
> to work. I have the following in my teaspoon_env.rb:
>
> Teaspoon.configure do |config|
>   config.formatters = "documentation"end
>
> And in my Guardfile:
>
> guard :teaspoon, cmd: "spring teaspoon -f=documentation" do
>   watch(%r{^app/assets/javascripts/(.+).js}) { |m| "#{m[1]}_spec" }
>   watch(%r{^spec/javascripts/(.*)})end
>
> And yet I keep getting dot format.
>
>
> <https://camo.githubusercontent.com/0e93d938ec7b3786cf0535e67fba383a8989dfb4/687474703a2f2f636c7273696768742e636f2f726c2f696f3932767a396b64682e706e673f2b>
>
> Any idea what I'm doing wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modeset/teaspoon/issues/302>.
>



-- 
*Jonathan Kang*
Software Engineer
Los Angeles, California
Tweets <http://twitter.com/zenjonny>
LinkedIn <https://www.linkedin.com/pub/jonny-kang/55/456/289>

**Comment by coderjonny** [comment]
try
```
  config.formatters = ["documentation"]
```

**Comment by jejacks0n** [comment]
yeah, I think that's probably it.. thanks @coderjonny.

It's an array because multiple formatters can be used -- to generate artifacts and console output.

**Comment by ryanlntn** [comment]
Switching to `config.formatters = ["documentation"]` doesn't have any effect.

**Comment by coderjonny** [comment]
Hmm it could have something to do with that guard cmd

On Monday, February 2, 2015, Ryan Linton <notifications@github.com> wrote:

> Switching to config.formatters = ["documentation"] doesn't have any
> effect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modeset/teaspoon/issues/302#issuecomment-72556077>.
>


-- 
*Jonathan Kang*
Software Engineer
Los Angeles, California
Tweets <http://twitter.com/zenjonny>
LinkedIn <https://www.linkedin.com/pub/jonny-kang/55/456/289>

**Comment by ryanlntn** [comment]
I think you may be right. Running the same command outside of guard produces the correct format:

![](http://clrsight.co/rl/e3gtoaspyy.png?+)

**Comment by jejacks0n** [comment]
:-/ hmmmm... I wrote the guard-teaspoon gem as a helper for people to get started, but it seems like it requires more maintenance than the community that uses it can provide. I don't use guard, and so only took an initial stab at it.

My guess is that the options that make it through to teaspoon are not correct, or are being overridden by guard -- which I believe is probably the case.

**Comment by ryanlntn** [comment]
Yeah it looks like there's already an issue over there too: https://github.com/modeset/guard-teaspoon/issues/33

If I get some time I might take a look at it and see if I can figure out why the options aren't making it through. If not, dot format will have to do. :wink:

**Comment by jejacks0n** [comment]
I think the guard-teaspoon project is overriding those things, so you may be able to configure it differently on that end.
