### ISSUE TITLE
CLI `filter` option for jasmine only matches beginning of spec name

### ISSUE THREAD

**Issue by bootleq** [modeset/teaspoon#304]
Current implementation only takes specs whose full name match filter at beginning, as valid matches.
https://github.com/modeset/teaspoon/blob/master/app/assets/javascripts/teaspoon-jasmine.js#L1168

I think it'd be nice to allow match at any position, take qunit as a reference:
https://github.com/jquery/qunit/blob/1d44eb38052d25d97a631b9711e481303fc472b6/src/test.js#L375

**Comment by jejacks0n** [comment]
This is not within the concern of teaspoon, as teaspoon supports what the framework supports.

**Comment by jejacks0n** [comment]
actually, I take that back -- it might be possible, and we'd accept a PR with this implemented.
