### ISSUE TITLE
tests aren't running in the browser when using custom boot_partial

### ISSUE THREAD

**Issue by TrangPham** [modeset/teaspoon#306]
Hi

I'm currently trying to run the tests in the browser and use a custom boot_partial

In my `teaspoon_env.rb` I've set:
``` Ruby
  config.fixture_paths = ["spec/javascripts/fixtures"]
  suite.boot_partial = "/boot"
```

And I have `spec/javascripts/fixtures/_boot.html.erb` which contains one `javascript_include_tag`

When I run `rails s` and visit `localhost:3000/teaspoon/default`, nothing is rendered. The javascript file is loaded though.

Am I not supposed to be able to see the tests results as I normally would without the `boot_partial`?

Any help is appreciated. Thank you :)

**Comment by jejacks0n** [comment]
I can't tell without seeing it, so try and base your boot partial off the one in the gem. Load that, see what's loaded, make a small adjustment, see if it works, etc.. my guess is that you're not telling teaspoon to execute though.

**Comment by TrangPham** [comment]
Ah Thank you!
