### ISSUE TITLE
Circle CI seems to not like to run teaspoon reliably

### ISSUE THREAD

**Issue by jejacks0n** [modeset/teaspoon#312]
Consolidating these issues:

https://github.com/modeset/teaspoon/issues/229
https://github.com/modeset/teaspoon/issues/303

**Comment by jedschneider** [comment]
It seemed this was an issue on travis for a while as well but it seemed to resolved with some upgrades to travis CI.
I made a 5 minute effort to figure out what had changed on travis, but they stopped updating their changelog over a year ago. This run is from 3 months ago:

```
Finished in 1 minute 29.07 seconds
1145 examples, 0 failures, 5 pending
** Invoke teaspoon (first_time)
** Invoke environment 
** Execute teaspoon
Starting the Teaspoon server...
>> Thin web server (v1.3.1 codename Triple Espresso)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:50391, CTRL+C to stop
Teaspoon running default suite at http://127.0.0.1:50391/teaspoon/default
Error: ActionView::Template::Error: execution expired
```

**Comment by jedschneider** [comment]
my guess is that they upgraded the selenium driver.

**Comment by jejacks0n** [comment]
I believe this is fixed in master, so if anyone wants to give it a shot to see if they can reproduce it that'd be awesome. @jedschneider?

I'm unsure if it's related, but it may be, and it had to do with file order on linux not being the same as os x.

**Comment by jejacks0n** [comment]
@jedschneider you never checked back in about this. Closing it, but feel free to provide your results. Master now is considerably different, but that problem should've been fixed with the ordering of files.
