### ISSUE TITLE
Chai config set threshold length

### ISSUE THREAD

**Issue by bierik** [modeset/teaspoon#319]
I got teaspoon 0.8.0

According to http://chaijs.com/guide/styles/ it's possible to set the threshold length.

So I was trying to set:
```javascript
chai.config.truncateThreshold = 0;
```
But I got no config object on chai.

In https://github.com/chaijs/chai/blob/1.9.1/lib/chai/config.js the config was introduced.
So I guess the problem could be an outdated chai version (Current: 1.8.1).
Are there any plans for updating chai. Or is it possible to update by myself?

**Comment by jejacks0n** [comment]
There's 1.10 in there. You can also add whatever support libraries you want.
