### ISSUE TITLE
loading javascript fixture data doesn't appear to work

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#330]
if I have this file (fakeGraphData.js):
```
var FAKE_ED_GRAPH_DATA = {
  'dates': ['2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
    '2014-08', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02', '2015-03'],
  'high': {
    'org': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2],
    'all_average': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2]
  },
  'medium': {
    'org': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2],
    'all_average': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2]
  },
  'low': {
    'org': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2],
    'all_average': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2]
  }
};
```
and I do
    this.fixtures = fixture.load('index.html', 'fakeGraphData.js');

The variable FAKE_ED_GRAPH_DATA is not 'on the page'

In the chrome console I see:
undefined: {undefined: [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2]}

**Comment by jejacks0n** [comment]
you can't load javascript with the fixtures.. it doesn't eval it, and so your var won't get processed. either load your js file in your test run like you would load any other javascript, or use a proper json format.

**Comment by rstudner** [comment]
So in the documentation, when it demonstrates loading "fixture.js" what exactly was happening there?

**Comment by jejacks0n** [comment]
you mean here: https://github.com/modeset/teaspoon#example-usage -- where it clearly uses .json and not .js?

**Comment by rstudner** [comment]
Sure - what would be in that file for example, that a test then could reasonably expect to be able to use?

Just trying to use this awesome framework and work and clarify how parts of it work -- not sure why you keep responding so aggressively.

**Comment by jejacks0n** [comment]
sorry if it comes across that way, just trying to give you the most concise information. if you have javascript, load it as a dependency of your test. if you have json data, load it via fixtures.

**Comment by jejacks0n** [comment]
either works in your case depending on what you want, but when I say the fixtures don't eval javascript, it should be clear what the intent is. it's to load raw data, not javascript that is parsed.

**Comment by rstudner** [comment]
Totally understand -- and this is opensource which means people (like me) should be happy with the docs we get (if they exist at all haha).

I guess i'm just at a loss for how "loading JSON as fixture data" could actually/possibly help with a test if I can't set it to a javascript variable (i.e. javascript code) while i'm at it haha.  I don't get how 'load raw data' actually could help with writing a test case, if I can't reference the raw data :) 

Clearly i'm missing the obvious -- sorry.

No biggie -- I moved it into my tests, just always looking to explore more about what I can/can't pull off from a reuse POV etc.

**Comment by jejacks0n** [comment]
ok, if the documentation isn't clear, I don't know how to help you.

data.json
```json
{
  'dates': ['2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
    '2014-08', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02', '2015-03'],
  'high': {
    'org': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2],
    'all_average': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2]
  },
  'medium': {
    'org': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2],
    'all_average': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2]
  },
  'low': {
    'org': [1, 2, 3, 2, 1, 2, 3, 2, 1, 2, 3, 2],
    'all_average': [3, 2, 1, 2, 3, 2, 1, 2, 3, 2, 1, 2]
  }
}
```

``javascript
fixture.load('data.json')
// within your tests you will have fixture.json[0] -- which is that variable.
```

**Comment by rstudner** [comment]
I found in the pre block, of the preload function example, fixture.json[0].  I had missed that prior -- my bad.  (and searching the page for fixture.json[ doesn't find it either due to the pre block).

Sweet!  thanks :)
