### ISSUE TITLE
Teaspoon Hooks are called twice from setup

### ISSUE THREAD

**Issue by arinhouck** [modeset/teaspoon#332]
Selenium (2.45.0 and 2.43.0 tested)
Teaspoon (0.8.0 and 0.9.1 tested)
Browsers tested (firefox, chrome)
Ruby 2.2.0
Rails 4.1.0

I am only calling the hook once on setup of one test and I put a debugger right after that. It still puts the message in console twice.

If needed any other information let me know.

**Comment by jejacks0n** [comment]
Fixtures or hooks? Thanks for the detailed info.

**Comment by arinhouck** [comment]
Sorry meant, "Teaspoon.hook".

**Comment by arinhouck** [comment]
Did you have any feedback or suggestions?

**Comment by mikepack** [comment]
Fixed on master. Can you give it a try? Details on how to use master can be found here: https://github.com/modeset/teaspoon#status
