### ISSUE TITLE
General FAQ on when command line teaspoon vs "localhost:3000/teaspoon" results differ

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#352]
Sorry -- not sure where to ask questions.

I'm having an issue where I can go to localhost:3000/teaspoon and run specs... and all 234 of them pass.

But, when I run it from the command line.. like 47 of them fail.  It "appears" based on the limited error output, that it has to do with not all the JS loading (or too much loading even if I do --filter)

(RAILS_ENV=test teaspoon doesn't change things).

a) Any fairly common reasons this is true?
b) Is there a way to get teaspoon's command line to spit out a heck of a lot more info (like all the http-esque requests / phantomjs world etc)

Thanks!

**Comment by jejacks0n** [comment]
try it with something like selenium webdriver (covered in the wiki). I'd guess that your version of phantomjs might not support something that you're trying to handle -- a polyfill will usually fix this.
