### ISSUE TITLE
console.log on selenium does not print when running the CLI

### ISSUE THREAD

**Issue by mikepack** [modeset/teaspoon#356]
Selenium doesn't provide support for accessing `console.log`s.

One way around this would be to override `console.log` to call `Teaspoon.hook`, like this:

```javascript
console.log = function() {
  Teaspoon.hook("log", {messages: arguments});
}
```

Calling `console.log` will call the hook defined in your `teaspoon_env.rb`, which could then print out the message:

```ruby
suite.hook :log do |payload|
  payload.messages.each do |message|
    puts message
  end
end
```

**Comment by EddieOne** [comment]
Is that the solution or the question? Facing the same problem.
