### ISSUE TITLE
Broken running on ruby < 2

### ISSUE THREAD

**Issue by pbcomm** [modeset/teaspoon#361]
Throws errors on start up:

SyntaxError: .rvm/gems/jruby-1.7.19@global/gems/teaspoon-1.0.0/lib/teaspoon/exceptions.rb:9: syntax error, unexpected tLABEL
    def initialize(msg = nil, searched:)
                                       ^
          require at org/jruby/RubyKernel.java:1071

I'm using jruby 1.7.19 (1.9.3p551)

**Comment by mikepack** [comment]
Version 1.0.2 should fix this. Run a bundle update.

**Comment by pbcomm** [comment]
Thanks, works great!
