### ISSUE TITLE
Any mechanism for 'overly verbose output'

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#365]
I have a set of tests running locally on a variety of developer (osx) machines.

Oddly, on the jenkins centos box -- they fail.

Also very oddly, when I run them locally, 250 of them pass.

On the jenkins box, 452 of them fail ;)  (there aren't 452 of them haha)

So, basically, i'm just trying to think of any way I can get bin/rake teaspoon to spit out a heck of alot more output as it is trying to run.. and i'm hoping anyone here has some hints as to how to do that :)

Thanks!

**Comment by mikepack** [comment]
What type of output are you looking for? You can run `teaspoon --format documentation` to output your spec details, but I assume that's not what you're looking for.

**Comment by rstudner** [comment]
Mike - yeah, not what I was looking for but thanks.  I started making use of Magic Lamp, and despite all the tests running on every developer box etc.. for some reason, on the jenkins centos box, all the tests that use magic lamp now fail.  And, since there is so little debugging/bootstrapping/I don't even know what I am looking for (hah) output, I can't seem to track down why this is the case.

**Comment by mikepack** [comment]
I've never used Magic Lamp but if you can create an app that reproduces the problem I'll happily take a look.
