### ISSUE TITLE
couldn't find the gem

### ISSUE THREAD

**Issue by dftaher** [modeset/teaspoon#366]
doing 'gem install teaspoon-framework' as per change log and getting the following error:

ERROR:  Could not find a valid gem 'teaspoon-framework' (>= 0) in any repository

**Comment by mikepack** [comment]
The word "framework" should be replaced with the name of the testing framework you're using. From the changelog, check the second line:

```
Change your Gemfile to use "teaspoon-framework" instead of "teaspoon".
eg: If you are using Mocha, this would be gem 'teaspoon-mocha'
```

**Comment by mikepack** [comment]
The available gems are `teaspoon-jasmine`, `teaspoon-mocha` and `teaspoon-qunit`.
