### ISSUE TITLE
Configure Spec Directory

### ISSUE THREAD

**Issue by Pezmc** [modeset/teaspoon#369]
I'm attempting to migrate a project from an older jasmine gem to teaspoon and would love be able to use our existing `/test/javascript/` directory over `/specs`.  Skimming your code it looks like it's hardcoded, or have I missed something? If not, consider it a feature request!

I note it's possible to configure the spec directory, but really I'd like to move teaspoon_env

**Comment by mikepack** [comment]
Correct. It also checks for checks in `test/javascripts`. This is configurable via `asset_paths` (see the [config options](https://github.com/modeset/teaspoon/wiki/Teaspoon-Configuration#general-configuration-directives))

If you want to specify where to find `teaspoon_env.rb`, you can use the `TEASPOON_ENV` environment variable, eg:

```bash
TEASPOON_ENV=jstests/teaspoon_env.rb teaspoon
```
