### ISSUE TITLE
Can't find teaspoon-framework gem

### ISSUE THREAD

**Issue by rapheld** [modeset/teaspoon#374]
The [CHANGELOG](https://github.com/modeset/teaspoon/blob/master/CHANGELOG.md) for 1.0.0 states to use the new gem name `teaspoon-framework`, but bundler can't find it. Somewhere else other than rubygems?

```
> bundle
Fetching gem metadata from https://rubygems.org/............
Could not find gem 'teaspoon-framework (>= 0) ruby' in any of the gem sources listed in your Gemfile or installed on this machine.
````

**Comment by mikepack** [comment]
Take a look at the next line in the changelog that indicates that you need to use `teaspoon-jasmine`, `teaspoon-mocha` or `teaspoon-qunit`. Substitute the word "framework" in that sentence for the framework you're using.
