### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by rstacruz** [modeset/teaspoon#376]
Would you guys be interested in a newer look for Teaspoon?

![](https://cloud.githubusercontent.com/assets/74385/8079359/7bf45454-0f96-11e5-897d-b1ec20edec19.png)

**Comment by mikepack** [comment]
Dig it. I wouldn't mind an updated look. @jejacks0n, what do you think?

**Comment by jejacks0n** [comment]
Looks good, but let me think on it. Here's my train of thought thus far... Initially I thought it's too white, and I don't like the large margins unless they do something nice at lower resolutions.

I often run teaspoon with the dev tab to the right, and the margins just eat into space that's useful. But on the other hand, it kinda grows on me, so I can't decide just yet. I'm unsure what the [?] is at the bottom as well -- can you explain?

**Comment by jejacks0n** [comment]
Oh, I'd also need to see the alternate views (only failures), and results for pending and failures when the full report is generated.

**Comment by rstacruz** [comment]
The `(?)` at the bottom is just an artifact of our project's build... that's Intercom.io's button somehow making its way to our teaspoon tests haha.

of course the margins are collapsible...  shouldn't be hard to make it responsive. btw, isn't the large "Teaspoon" text extraneous at this point?

**Comment by rstacruz** [comment]
there's a lot of work to get this working btw... CSS is the easy part, but the canvas progress bar would have to be modified a lot to make it render a simpler graph.

(actually, i'm pretty confident it can be implemented without canvas... just plain CSS.)

**Comment by jejacks0n** [comment]
Yeah, the code to accomplish what I wanted in css was uglier than the canvas approach (a simpler design would fix that, but not as is). If you want to design it, and provide the things outlined, I'm happy to consider and potentially implement it with potential adjustments.

**Comment by mikepack** [comment]
Going to close for now, but would love to see progress on this in the form of a PR.
