### ISSUE TITLE
Favicon is being requested and not needed.

### ISSUE THREAD

**Issue by jejacks0n** [modeset/teaspoon#377]
So, somebody brought this up a bit ago, and I thought it was a cool idea. First, the favicon is being requested when it's not needed. If you don't have one, you see a 500 or 404.

As a first pass we should at least disable that request.
```html
<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
```

And as a follow up, we could put a little blue -> red or green favicon as the tests run and complete.

**Comment by mikepack** [comment]
I like the changing favicon idea. Can we use the svgs we have to create the icons?

**Comment by jejacks0n** [comment]
I think we can just swap out that href with a base64 encoded url.. though, favicons are cached heavily, but that's where we can start. Do you want me to look at it, or is it something that interests you?

**Comment by mikepack** [comment]
If you could look into that, it would be awesome. You seem to have a strong grasp on how to accomplish it.

**Comment by jejacks0n** [comment]
I'll actually look into this tomorrow.

**Comment by jejacks0n** [comment]
I clearly never looked into this, so I'm going to sweep this failure under the rug. ;-P
