### ISSUE TITLE
Total test count is not set for reports

### ISSUE THREAD

**Issue by crgee** [modeset/teaspoon#378]
For `Version 1.0.2` the total test count is blank on each report. 

We came across this when our TAP reader failed to parse a report. In our particular case all tests are passing and there is no console output to influence parsing. I double checked the issue by confirming the value was missing from multiple formats:
* TAP Report: 1..
* JUnit Report: testsuite name="default" tests="" time="2015-06-12T18:26:51.309Z"
* Json Report: {"type":"runner","total":null,"start":"2015-06-12T18:49:43.042Z","_teaspoon":true}

This seems to be due to the report total not being set upstream from this [point](https://github.com/modeset/teaspoon/blob/master/lib/teaspoon/formatter/base.rb#L26). (Probably an obvious point, but I figured any help would be beneficial, and I am out of time myself. :sweat:)

Thanks, and fantastic work on the latest releases - cleaned up our infrastructure greatly.

**Comment by mikepack** [comment]
Thanks for the report @crgee. I've pushed a fix up to master to solve this. It will go out with the 1.0.3 release (no date set yet). In the meantime, you can point your Gemfile at master.

**Comment by crgee** [comment]
Great, thanks
