### ISSUE TITLE
Fixture has <tr> and <td> stripped out when not in <table>

### ISSUE THREAD

**Issue by drogar** [modeset/teaspoon#382]
I often return HTML partials, such as a table row, in ajax interactions.

Given a fixture named 'whatever.html' that looks like:
```
<tr>
  <td>Some thing</td>
</tr>
```
Then, when calling `loadFixture('whatever.html')` the `tr` and `td`s are stripped, leaving only `Some thing`.

Is it possible to return the verbatim html?

**Comment by jejacks0n** [comment]
It's removed when inserted into the DOM/converted to elements via jquery. It's not really a fixture thing, it's a valid HTML thing.

I'll think on a way to circumvent that.

---
Jeremy Jackson
303-507-6846

**Comment by mikepack** [comment]
I don't think there's a good way around this other than restructuring the markup you're returning. Even `innerHTML` suffers from this problem.

**Comment by drogar** [comment]
OK - Thanks for trying!

**Comment by mikepack** [comment]
@drogar, if you have jQuery in your project (Teaspoon doesn't ship with it), this should work for you once #389 lands.
