### ISSUE TITLE
Ability to specify the host on which server runs, e.g http://me.dev:54614/teaspoon

### ISSUE THREAD

**Issue by luis-ca** [modeset/teaspoon#383]
In previous versions, Teaspoon allow the host to be specificed via the server_host configuration param. Is there a reason for this to have been removed?

**Comment by mikepack** [comment]
In what version did we have a `server_host` config? I can't find it looking all the way back to 0.5. Also, what's your use case? The booted server is for headless testing, but are you using it for something other than that?
