### ISSUE TITLE
Returns 0 exit code if phantom fails to start

### ISSUE THREAD

**Issue by statianzo** [modeset/teaspoon#393]
When setting up CI, I was running teaspoon on a machine missing `libfreetype`, which phantom requires to run. This error was spit out to the console:

```
/home/runner/.phantomjs/1.9.8/x86_64-linux/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
```

Teaspoon still gave an exit code of 0 and my CI considered the build as a pass.

My desired behavior would be that phantom failing to start would give a non-zero exit code so that CI would've failed.

**Comment by mikepack** [comment]
Thanks a ton for submitting this issue, Jason. It should be resolved on master and will go out with the next release.
