### ISSUE TITLE
"Can't find variable: Teaspoon" because of wrong assets URI after upgrading to 0.8.0

### ISSUE THREAD

**Issue by agis-** [modeset/teaspoon#399]
Hello.

I've performed the following steps to upgrade from 0.7.9 to 0.8.0 (Rails 3.2.22). I've followed the [described steps in the CHANGELOG](https://github.com/modeset/teaspoon/blob/master/CHANGELOG.md#upgrade-steps-1)  and I get the following error when trying to run the tests:

```shell
$ RAILS_ENV=test bundle exec teaspoon --suite=default
ReferenceError: Can't find variable: Teaspoon
  # http://127.0.0.1:52072/teaspoon/default?reporter=Console:11 -- global code

ReferenceError: Can't find variable: Teaspoon
  # http://127.0.0.1:52072/teaspoon/default?reporter=Console:75 -- global code

Failed to load: http://127.0.0.1:52072/teaspoon/default?reporter=Console
```

The exception is thrown when [`#execute`](https://github.com/modeset/teaspoon/blob/v0.8.0/lib/teaspoon/console.rb#L21) calls [`#execute_without_handling`](https://github.com/modeset/teaspoon/blob/v0.8.0/lib/teaspoon/console.rb#L28). The exception is then rescued a [little later](https://github.com/modeset/teaspoon/blob/v0.8.0/lib/teaspoon/console.rb#L25).

Grabbing the backtrace of the exception at that point, gives us:

```shell
> e.backtrace
=> ["/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/runner.rb:53:in `on_exception'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/runner.rb:34:in `notify_formatters'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/runner.rb:17:in `process'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:24:in `block in run_specs'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:31:in `each'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:31:in `block in run'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:31:in `popen'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:31:in `run'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/drivers/phantomjs_driver.rb:23:in `run_specs'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:45:in `run_specs'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:35:in `block in execute_without_handling'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:33:in `each'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:33:in `inject'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:33:in `execute_without_handling'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:21:in `execute'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/console.rb:17:in `failures?'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/lib/teaspoon/command_line.rb:13:in `initialize'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/bin/teaspoon:6:in `new'",
 "/Users/agis/.gem/ruby/2.1.5/gems/teaspoon-0.8.0/bin/teaspoon:6:in `<top (required)>'",
 "/Users/agis/.gem/ruby/2.1.5/bin/teaspoon:23:in `load'",
 "/Users/agis/.gem/ruby/2.1.5/bin/teaspoon:23:in `<main>'"]
```

I've added my relevant configuration files in [this gist](https://gist.github.com/agis-/7b92dea5b057381db0eb) (also included the actual location of the files).

Note that before I've made the changes to go to 0.8.0, my spec_helper file was actually named`spec/javascripts/spec_helper.js.coffee` (notice the `.js` part); not sure if this is relevant.

**Comment by agis-** [comment]
I've followed the steps described in https://github.com/modeset/teaspoon/issues/397#issuecomment-127433338 and I get this page: http://f.cl.ly/items/3U0s300B2n0t0E1Z2r3Z/Image%202015-08-07%20at%203.30.19%20PM.png (I've slightly changed the paths but they look fine anyway).

**Comment by agis-** [comment]
I think that I've found the issue but not sure why it's happening. The host that Teaspoon uses is wrong:

![img](http://f.cl.ly/items/2G45111T2h1D2l073h0B/Image%202015-08-07%20at%203.44.45%20PM.png)

**Comment by agis-** [comment]
Just tried running teaspoon without the `RAILS_ENV=test` part and it works!

Are we supposed to run this command on development or test environment? Note that this was running with `RAILS_ENV=test` up until 1.7.x and on our CI server.

**Comment by jejacks0n** [comment]
Check your test env, it's probably oddly configured. Only thing that makes sense.

---
Jeremy Jackson

**Comment by agis-** [comment]
Yep, just found out that we're doing this in `config/environments/test.rb`:

```ruby
config.action_controller.asset_host = "http://assets.test.host"
```

Which is not wrong in terms of the Rails app but it breaks up with teaspoon. However, the question is: what is the *standard* way to run the command (supposing this is about a CI server)? With RAILS_ENV='test' or without it?

**Comment by jejacks0n** [comment]
Do you have any integration tests? Like cucumber or capybara? Those wouldn't work either, because your asset host does not exist. How is that a correct configuration? Locally, and via the browser it should run using the dev env because you get the shared asset cache. On CI, it should be test. To be honest, I don't see how it ever worked.

---
Jeremy Jackson

**Comment by agis-** [comment]
Not sure but since it resolved I'm closing this. I've left the asset host to the default one. Thanks.
