### ISSUE TITLE
How to make default suite optional

### ISSUE THREAD

**Issue by rn2dy** [modeset/teaspoon#408]
Is there a way to disable default suite since I only use named suites? AFAK the default suite exists so that named suites can inherit from it.

Or maybe I should restructure my tests?

**Comment by jejacks0n** [comment]
There's not an easy way, no. Sorry.

---
Jeremy Jackson

**Comment by robinpokorny** [comment]
I had this problem as well. The *default* suite caused some problems when run.

So I set `suite.matcher = ""` in the *default* suite configuration and override the *matcher* in the named suites. This way *default* is still present but it is empty.
