### ISSUE TITLE
The bundled version of expect.js is outdated

### ISSUE THREAD

**Issue by jsilland** [modeset/teaspoon#409]
teaspoon-mocha 2.2.4 ships with expect.js 0.1.2, which is out of date – it was released 4 years ago. The latest version is 0.3, as per https://github.com/Automattic/expect.js — It is semantically non-breaking but I haven't verified that myself.

**Comment by mikepack** [comment]
I've pushed a commit to add expect.js 0.3.1. It will go out with the next release of teaspoon-mocha. To reduce upgrade surprises, I have not replaced the existing version of expect.js. So, `//= require support/expect` will still load 0.1.2, while `//= require support/expect-0.3.1` will load 0.3.1.
