### ISSUE TITLE
odd XML output error/issue

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#410]
rarely, i'll get an error that my teaspoon tests failed, because the output XML document is invalid (it lacks a closing tag(s) and more)

So I pulled it up, and compared it to a prior successful run.

Fail first 3 lines:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jasmine"><testsuite name="" tests="275">
<testcase classname="notifications_settings/index showing organization notifications initial state" name="should not show new form"></testcase>
```
Success first 3 lines:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Teaspoon">
<testsuite name="default" tests="235" time="2015-09-23T14:57:05.942Z">
```

**Comment by jejacks0n** [comment]
Does it have to do with the fail fast configuration? Is there more than one suite?

Without more info, I can't be of much help, but it hasn't been reported before. Would be happy if you wanted to dive in and see if you can figure it out and provide some resolution.

https://github.com/modeset/teaspoon/blob/master/lib/teaspoon/formatter/junit.rb

**Comment by rstudner** [comment]
I'll get more info pulled together today and post it up (sorry initial comment was sparse on that).

It is interesting, looking at the junit.rb, that somehow I ended up with testsuites name="jasmine" at all (since that doesn't appear possible in the above code heh)

**Comment by jejacks0n** [comment]
Any updates?

**Comment by rstudner** [comment]
No.  I haven't been able to reproduce it.  The fact that it ever happened (since the .rb code doesn't seem to even allow for the possibility) is a head scratcher.  I'll close this and when I next see it, come back hah.
