### ISSUE TITLE
Teaspoon and the Asset pipeline (re: a react question hah)

### ISSUE THREAD

**Issue by rstudner** [modeset/teaspoon#432]
I was wondering if teaspoon could make sure of the various transpilers in the asset pipeline.. specifically, why I can't write:

myComponent_spec.js.jsx 

and thus put JSX statements etc into my tests.  Would make the testing of React components much much easier and since React is so popular, would give some more legs to the use cases teaspoon happily supports.

Thoughts?

**Comment by jejacks0n** [comment]
if they're part of sprockets, they get transpiled.

**Comment by rstudner** [comment]
Hrm.  I'm having mixed results.

I have a file:
AjaxSuccessFailureButton_spec.js.jsx in spec/javascripts/components

Sometimes it shows up in the list of tests.. sometimes it just... magically vanishes hah.

I can see 20 of my various test suites.. but this one is just... missing...?

No errors in console etc.

**Comment by jejacks0n** [comment]
Ah, sorry. You can read about [Teaspoon configuration](https://github.com/modeset/teaspoon/wiki/Teaspoon-Configuration#suite-configuration-directives), specifically the `matcher` configuration directive.

**Comment by jejacks0n** [comment]
I'm unsure why your spec would be a .jsx, but have at it. =)

**Comment by rstudner** [comment]
Hah yeah.. just for React stuff, especially with multiple components, it just way easier to render them into the DOM/configure their props using the JSX syntax.  The "pure js" React syntax is fine for doing really trivial things, but if you want to make a mock component (re: chunk of DOM) to use with a react widget (think "yield") it gets to be insane without JSX.

**Comment by jejacks0n** [comment]
Sounds cool. I haven't had the opportunity to get into React yet. Hope you're sorted now though. =)

**Comment by rstudner** [comment]
Yep, is working perfectly.  I had the default matcher (as you suspected) and just forgot about that entire part of the Docs since it'd been so long since I'd had to get in there.

Thanks for the prompt responses and help -- much appreciated.

I'll try to update your docs (if you like) with a little subsection on 'setting up to test React' if you like based on these little config tweaks etc.

**Comment by jejacks0n** [comment]
Yeah man, feel free to create a wiki article for it -- would be super valuable to others I'm sure.
