### ISSUE TITLE
How to override Mocha's interface (UI setting)?

### ISSUE THREAD

**Issue by christian-schulze** [modeset/teaspoon#438]
Is it possible to override Mocha's interface? See https://mochajs.org/#interfaces, and https://mochajs.org/#browser-configuration.

Currently it looks like the interface is hard coded to `bdd` here: https://github.com/modeset/teaspoon/blob/cdf46b24676c093f7a2b0ed8e8e473dd89a47564/teaspoon-mocha/lib/teaspoon/mocha/assets/teaspoon/mocha/intiialize.coffee.

I would like to, for example, use the `bdd-lazy-var` UI defined here: https://github.com/stalniy/bdd-lazy-var.

**Comment by christian-schulze** [comment]
Have found a solution. With some pocking around `window.env` by adding `(console.log prop + ': ' + value) for prop, value of window.env` to `spec_helper.coffee`, I found:
```javascript
ui: function (ui) {
  Mocha.prototype.ui.call(this, ui);
  this.suite.emit('pre-require', global, null, this);
  return this;
}
```

Calling `window.env.ui('bdd-lazy-var')` in `spec_helper.coffee` works perfectly.

Perhaps this could be added to the Mocha wiki page to help future developers?

**Comment by jejacks0n** [comment]
That's good info. Can I understand why you want to do this? I don't know that things will work when you change this, and am curious how you're using it.

---
Jeremy Jackson

**Comment by christian-schulze** [comment]
I'm coming from an **rspec** background, where you can define lazy loaded variables using the `let` statement, and also assign a lazily loaded `subject` which you test in your assertions.

Whether this sort of feature addition to Mocha is valid is up for debate, so lets leave that for another discussion.

The [bdd-lazy-var](https://github.com/stalniy/bdd-lazy-var) module allows injecting this behaviour into Mocha via the `ui` interface, which is a well defined api. After which you can now write specs like this:
```coffeescript
describe 'Widget', ->
  subject ->
    new Widget(get('color'), get('price'))

  describe '#build', ->
    def 'color', -> 'black'
    def 'price', -> 50

    it 'assigns the color', ->
      expect(subject().color).to.equal('black')

    it 'assigns the price', ->
      expect(subject().price).to.equal(50)
```
A very contrived example, but demonstrates how you can dry up the assertions.

I've actually switched to using the [lazy-bdd](https://github.com/ghempton/mocha-lazy-bdd) implementation as the projects code is cleaner and more easily understood. An example spec using `lazy-bdd` looks like:
```coffeescript
describe 'Widget', ->
  subject ->
    new Widget(@color, @price)

  describe '#build', ->
    lazy 'color', -> 'black'
    lazy 'price', -> 50

    it 'assigns the color', ->
      expect(@subject.color).to.equal('black')

    it 'assigns the price', ->
      expect(@subject.price).to.equal(50)
```

**Comment by christian-schulze** [comment]
Will close this as everything is good.

**Comment by jejacks0n** [comment]
Thanks for the info!
