### ISSUE TITLE
Regression: Teaspoon 1.1.2 does not parse `//= require` directives when config.assets.debug = false

### ISSUE THREAD

**Issue by ajb** [modeset/teaspoon#447]
(Originally commented in https://github.com/modeset/teaspoon/issues/443#issuecomment-170619612)

Isolated test case repo here: https://github.com/ajb/teaspoon_bug

- Run `rails server` and visit http://localhost:3000/teaspoon`. None of the assets that are required in `spec_helper.coffee` are included.
- Next, change `config.assets.debug` to `true` in `config/environments/development.rb`. It works properly.

**Comment by jasper-lyons** [comment]
I am experiencing a very similar problem with the difference that changing the ```config.assets.debug``` doesn't seem to effect the outcome.

I will report back when I get some more info / figure out the problem.

teaspoon-jasmine: 2.3.4
teaspoon: 1.1.2
sprockets: 3.5.2
phantomjs: 2.0
rails: 4.2.5

**Comment by erichummel** [comment]
in my own testing I can confirm that require directives are not being used, however the flag that worked for me (admittedly Teaspoon 1.1.4) was the suite.expand_assets = true in teaspoon.env.

This *dramatically* slows down my jasmine suites, and I would very much like to be able to serve a concatenated javascript blob rather than each individual file.

**Comment by jejacks0n** [comment]
It seems likely to be related to some recent changes required by sprockets, but only a few people have reported it, so I'd like others to chime in if this is the case, so I can try and resolve it and capture it in a spec. More details are needed.

**Comment by erichummel** [comment]
Wow - quick response - thanks. I'll see if I can find some more information that would help.

**Comment by erichummel** [comment]
my front end guy locked our sass-rails gem to an old version, which in turn was locking an old version of sprockets (2.3.3) - I suspect that this may have contributed to this issue (though not for @ajb's example repo). I'm gonna tinker some and let you know.

**Comment by jejacks0n** [comment]
if you check https://github.com/modeset/teaspoon/blob/master/lib/teaspoon/engine.rb#L99 you'll see a kinda ugly hack in there to work around the restrictions of sprockets 3+ -- I have an open issue (https://github.com/rails/sprockets-rails/issues/297) on sprockets-rails to see if @rafaelfranca has thoughts, but haven't heard back yet.

**Comment by erichummel** [comment]
cool. I now understand why my front end guy tried the sass-rails upgrade and gave up, I've got some work on another thing I work on to do now so won't be able to finish my investigations til monday (i'm gonna be miles away from my computer over the weekend).

thank you for being so responsive @jejacks0n, I will do my best to help out as best I can on monday.

**Comment by jejacks0n** [comment]
Yeah, I agree with the changes they've made with sprockets 3.0.0, but it'll probably throw a few kinks in for engines that were utilizing the less strict behavior in development environments.

**Comment by erichummel** [comment]
heh yeah. judging by a few issues in their repo it does seem to be throwing some people for a loop.

**Comment by connorshea** [comment]
So we just ran into this, any updates?

**Comment by jejacks0n** [comment]
I still don't know what's happening, and have not seen it as of yet.. any ideas on what's happening? like, literally, you get a js file served to you where you can see `//= require [file]`?

**Comment by jejacks0n** [comment]
I'm not seeing this, so am closing it.. if someone else has more to add it would be great.
