### ISSUE TITLE
rubygems incorrect links

### ISSUE THREAD

**Issue by mrloop** [modeset/teaspoon#457]
https://rubygems.org/gems/teaspoon has incorrect links for `Source Code`  and `Documentation`. They both point to https://github.com/mintdigital/teaspoon

**Comment by jejacks0n** [comment]
Yeah, sadly we know, long story, name collision. If you know anybody at rubygems, or of a place where an issue can be opened, it would be nice to remove the abandoned gem to open the namespace back up.

**Comment by jejacks0n** [comment]
It appears one just needs to click edit and adjust them.. anyhow, got that resolved. Thanks for the heads up.
