### ISSUE TITLE
Rails 4.2.6: Asset was not declared to precompile

### ISSUE THREAD

**Issue by bmulholland** [modeset/teaspoon#466]
I just tried a rails upgrade, which seems to have triggered #443 again.

teaspoon 1.1.4, sprockets 3.5.2, ruby 2.2.3

rails 4.2.5.2: No issue
rails 4.2.6: "Asset was not declared to be precompiled in production."

I reproduced this with no other gem versions changing.

**Comment by jejacks0n** [comment]
have you checked with master?

**Comment by bmulholland** [comment]
@jejacks0n Apologies, thought I had. Looks like master fixed it. Do you know when a new gem version will be released with that fix?

**Comment by gaganawhad** [comment]
👍

**Comment by pjmelling** [comment]
+1

**Comment by jejacks0n** [comment]
Cheers for checking in.. I'll try to get a new version pushed this weekend.

**Comment by pjmelling** [comment]
Awesome! Thank you so much!

**Comment by gaganawhad** [comment]
thanks a bunch @jejacks0n
