### ISSUE TITLE
Fails silently on CLI runner when Rails is upgraded to 4.2.6

### ISSUE THREAD

**Issue by mathias** [modeset/teaspoon#467]
Hello,

I'm seeing this failure when we upgrade our Rails app to 4.2.6:

```
$ bundle exec teaspoon
Starting the Teaspoon server...
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: test
* Listening on tcp://127.0.0.1:62903
Teaspoon running default suite at http://127.0.0.1:62903/teaspoon/default
Failed to load: http://127.0.0.1:62903/teaspoon/default?reporter=Console
```

Is there any way to get a more verbose error here? Also, would this possibly have something to do with rake getting upgraded from `10.5.0` to `11.1.1` as part of this upgrade?

Running the rails server and navigating to localhost:3000/teaspoon still works fine, no Chrome inspector errors in console.

**Comment by adamrmelnyk** [comment]
Experiencing the same issue and using rake 11.1.1 and rails 4.2.6

Teaspoon fails silently after trying to start up.

**Comment by jejacks0n** [comment]
Try it with master?

So, I think it may be two fold -- Rake may be throwing an extra kink in there, but what's probably happening is that it fails because of issues around sprockets. In addition, it sounds like rake is gobbling up some information that used to be presented, but I have no idea how at this point.

**Comment by mathias** [comment]
That works, but I'd really like to be on a version off rubygems. Any chance of cutting a release?

**Comment by jejacks0n** [comment]
Well, that's how this all works right? I'll use this as an opportunity to explain. =) You see an issue, as a step one, you always try master, if that doesn't fix it you can open a PR with your fix, or open an issue -- the former being the better of the two -- obviously. Now, here's the important bit: if master is working, and is a notable improvement from the latest gem version, it's helpful to let us know by searching closed issues and adding a comment there so we know.

I don't have a plan to release the next version this weekend, but maybe early next week.
