### ISSUE TITLE
The install generator generates a coffeescript root file, but Sprockets 4 doesn't seem to support that anymore.

### ISSUE THREAD

**Issue by jejacks0n** [modeset/teaspoon#474]
https://github.com/rails/sprockets/issues/273#issuecomment-206415863

Looks like we'll need to update the install generator to not generate a `spec_helper.coffee`, and instead generate a `spec_helper.js`.

#473

**Comment by liseki** [comment]
We can now close this with the advent of [#478](https://github.com/modeset/teaspoon/pull/478).
