### ISSUE TITLE
Hook to run ruby script before tests start

### ISSUE THREAD

**Issue by ZackMattor** [modeset/teaspoon#483]
Is there a way to hook into teaspoon and run a ruby script before the jasmine tests execute? I want to generate some fixtures with ruby. Currently i'm doing it a hacky way in teaspoon_env.rb... but it gets called in rspec tests, etc.

**Comment by jejacks0n** [comment]
https://github.com/modeset/teaspoon#hooks

**Comment by ZackMattor** [comment]
Derp... thanks. But I seem to have another problem @jejacks0n ...

It seems like every hook I call seems to return a 500 in the request?...
<img width="890" alt="screen shot 2016-05-31 at 8 58 48 pm" src="https://cloud.githubusercontent.com/assets/552776/15695180/882cec8c-2772-11e6-8948-de63c490c00c.png">

```
    suite.hook :component_fixtures do
      puts "This should run..."
      TeaspoonFixtureGenerator.run("test_fixture")
      puts "Hmmm...."
    end
```

It gets all the way through the hook but returns the 500 for some reason.. I threw a `binding.pry` into the teaspoon controller#hook method to try and track it down and it got pretty deep...

<img width="841" alt="screen shot 2016-05-31 at 9 04 33 pm" src="https://cloud.githubusercontent.com/assets/552776/15695267/66d84fda-2773-11e6-8884-294a9608da09.png">

**Comment by jejacks0n** [comment]
Hey man, got the email notification for the comment you added and came here to check it out.. Looks like it's gone, so hopefully that means you got things working.
