### ISSUE TITLE
Hook produces ReferenceError: url is not defined 

### ISSUE THREAD

**Issue by RGreinacher** [modeset/teaspoon#493]
Hey!

I try to create a hook like so:

(*teaspoon_env.rb*, in `config.suite do |suite|`)
```
suite.hook :create_document do
      require 'factory_girl_rails'

      MyDocument.destroy_all

      FactoryGirl.definition_file_paths = ['./spec/factories']
      FactoryGirl.find_definitions
      FactoryGirl.create(:annotation_document)
    end
```

and call it in my *my_test_spec.coffee* with

```
before ->
  Teaspoon.hook('create_document')
```

This leads me to the following error in both, browser and CLI:

>  "before all" hook
> ReferenceError: url is not defined (http://localhost:3000/assets/teaspoon-mocha.self-b15d919...

What am I doing wrong? Thanks a lot! : )

**Comment by RGreinacher** [comment]
I filed the issue using teaspoon-mocha. Today I tried to use teaspoon-jasmine and I still get the same error. Via CLI I tried to call `Teaspoon.hook('test_hook')` in my *test_spec.coffee* and got `ReferenceError: Can't find variable: url`

```
suite.hook :test_hook do
  ap 'wow, such test!'
end
```

Interesting thing is that I nevertheless got the console output "wow, such test!" - so the hook is working, but throwing an error anyways.

**Comment by ZackMattor** [comment]
Yeah, I get this same error... I'm trying to dive into it today. Its all working as expected but throws a TON of errors when i'm running my test suite.

**Comment by jejacks0n** [comment]
so, it looks like this:

https://github.com/modeset/teaspoon/blob/master/app/assets/javascripts/teaspoon/hook.coffee#L22

That will let you know (and will in theory break a test) if the response isn't a 200.. but it's using a variable that's not defined `url`.

I'll try and get to this today.

**Comment by ZackMattor** [comment]
I solved my case. I will have a PR open when i get back from lunch.

`:success` is not a valid status code symbol so the server always returns 500.

**Comment by jejacks0n** [comment]
ah, yes.. it's :ok, not :success.

**Comment by jejacks0n** [comment]
but the underlying problem is still there with the url variable.

**Comment by ZackMattor** [comment]
@jejacks0n, I'm thining about not relying on the `url` variable, but returning an error message from the server with a `:not_found - 404` status code if there is no hook present (exactly what the hook.coffee throw was trying to show).

```
  def hook
    hooks = Teaspoon::Suite.new(params).hooks[params[:hook].to_s]

    if hooks.present?
      hooks.each { |hook| hook.call(hook_params(params[:args])) }
      head(:ok)
    else
      render status: :not_found, json: {err: "The `#{params[:hook].to_s}` hook is not defined in the `#{params[:suite].to_s}` suite "}
    end
  end
```

**Comment by ZackMattor** [comment]
Working error output.

![image](https://cloud.githubusercontent.com/assets/552776/17185212/332dc928-53fe-11e6-95bd-983111d26658.png)
